### ISSUE TITLE
Ability to define source

### ISSUE THREAD

**Issue by fhibler** [job/irrtree#2]
Hey,
The ability to define the source (IRR) would be very helpful as well. 

Thanks!

**Comment by job** [comment]
What would be the usecase? I can't envision how it would produce useful or complete output

**Comment by fhibler** [comment]
To specify where it pulls the information from, particular if you run your own IRRd without having a default output source defined.

**Comment by job** [comment]
That is already supported: `irrtree -h $your_own_irrd_host -p $port AS-COLOCLUE`

**Comment by job** [comment]
Let's chat on IRC, maybe I don't understand.

**Comment by job** [comment]
Added support for sources specification in 795c50e07b150da360924a0dbdfbab4023ab17e7
