### ISSUE TITLE
search of lowercase asN fails

### ISSUE THREAD

**Issue by troy2914** [job/irrtree#3]
Not uppercasing the search value results in false results
    irrtree -s as2914 AS-OPENTRANSIT
results in
    IRRTree (1.1.0) report for 'AS-OPENTRANSIT' (IPv4), using rr.ntt.net at 2015-07-12 04
:01
    NOT_FOUND: as2914 not present in AS-OPENTRANSIT or any of its members

but 
    irrtree -s AS2914 AS-OPENTRANSIT
returned
IRRTree (1.1.0) report for 'AS-OPENTRANSIT' (IPv4), using rr.ntt.net at 2015-07-12 03
:11
AS-OPENTRANSIT (31302 ASNs)
 +-- AS-INTEROUTE (29504 ASNs)
     +-- AS-WIFIWEB-TRANSITO (6 ASNs)
         +-- AS2914 (2489 pfxs)

**Comment by job** [comment]
Fixed in 4db9b198fb6e45f0a62b392fa0f5c77b1b93e618. thanks
